Develop/lab 3/add sql/sql scripts
DanielAverman/BSU_EDU_Practice pull request #2
Opened 2021-03-02 09:42 UTC by Daniil-com

2021-03-02 13:18 UTC, VeronikaYastr requested changes

2021-03-02 13:18 UTC, VeronikaYastr commented on sql/1. Создание/1. Создание_таблиц.sql
> +  likes Integer,
обычно int используется

2021-03-02 13:18 UTC, VeronikaYastr commented on sql/1. Создание/1. Создание_таблиц.sql
> +create table post(
Для всех полей, которые не могут быть пустыми (title, likes и т.д) в таблицах добавляется NOT NULL. Для лайков еще можно использовать DEFAULT 0 (потому что по дефолту они всегда будут равны 0 и при создании нового поста можно будет не указывать каждый раз это поле, оно будет заполняться автоматически)

2021-03-02 13:18 UTC, VeronikaYastr commented on sql/2. Запросы к post/3. посты одного автора.sql
> + where author in (SELECT id
ну можно было просто where author = 1 (ну по айди выбор). но так тоже норм) только выбор по имени все же лучше делать where name **=** 'Daniel'

2021-03-02 13:18 UTC, VeronikaYastr commented on sql/3. Запросы к users/2. пользователь по имени и паролю.sql
> + where name like 'Даниэль'
тут тоже лучше использовать = вместо like

2021-03-13 16:45 UTC, VeronikaYastr commented
Мои замечания тут уже две недели висят, будете их исправлять?)

2021-03-16 15:05 UTC, FireBelka commented
[1. Создание_таблиц.txt](https://github.com/DanielAverman/BSU_EDU_Practice/files/6149992/1._.txt)
Уже)

2021-03-24 06:07 UTC, VeronikaYastr commented
Тоже можно мержить

2021-04-02 18:35 UTC, merged