Лаба 4
DanielAverman/BSU_EDU_Practice pull request #3
Opened 2021-03-09 15:17 UTC by DanielAverman

Слезы и боль

2021-03-13 16:49 UTC, VeronikaYastr requested changes

2021-03-13 16:49 UTC, VeronikaYastr commented on src/main/resources/myFlywayConfig.properties
> +flyway.password=password
А зачем этот файл отдельно нужен, это же можно в application.properties прописать?

2021-03-13 16:49 UTC, VeronikaYastr commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +  likes int default 0,
not null не хватает

2021-03-13 16:49 UTC, VeronikaYastr commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +  created_at date,
тут тоже not null и для modified_at, author тоже

2021-03-13 16:49 UTC, VeronikaYastr commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +create table LOG(
почему капс локом оно написано?)

2021-03-13 16:49 UTC, VeronikaYastr commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +INSERT INTO users (ID,surname,NAME,PASSWORD,mail) VALUES
тут тоже не оч понятно почему некоторые столбцы большими буквами написаны?)

2021-03-16 15:28 UTC, FireBelka commented on src/main/resources/myFlywayConfig.properties
> +flyway.password=password
application.properties это также прописано

2021-03-16 15:29 UTC, FireBelka commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +  likes int default 0,
Фотографии может и не быть

2021-03-16 15:34 UTC, FireBelka commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +  created_at date,
обновлено

2021-03-16 15:34 UTC, FireBelka commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +create table LOG(
обновлено

2021-03-16 15:35 UTC, VeronikaYastr commented on src/main/resources/myFlywayConfig.properties
> +flyway.password=password
ну я к тому что может это убрать?)

2021-03-16 15:35 UTC, VeronikaYastr commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +  likes int default 0,
я про likes

2021-03-16 15:40 UTC, FireBelka commented on src/main/resources/db/migration/V1_1_0__my_first_migration.sql
> +  likes int default 0,
там default 0 прописано

2021-03-24 06:04 UTC, VeronikaYastr commented
Можно мержить

2021-03-24 06:07 UTC, VeronikaYastr commented
Можно мержить

2021-04-02 18:36 UTC, merged